/**
 * Created by: artDev
 * Copyright (c) 2025 artDev, SerpentSpirale, CADIndie.
 * For use under LGPL-3.0
 */
void glClearDepth(double depth);
void* glMapBuffer(GLenum target, GLenum access);
void glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params);
void glDebugMessageControl( 	GLenum source,
                               GLenum type,
                               GLenum severity,
                               GLsizei count,
                               const GLuint *ids,
                               GLboolean enabled);
void glMultiDrawElementsBaseVertex( 	GLenum mode,
                                       const GLsizei *count,
                                       GLenum type,
                                       const void * const *indices,
                                       GLsizei drawcount,
                                       const GLint *basevertex);
void glBindFragDataLocation(GLuint program,
                            GLuint colorNumber,
                            const char * name);
void glGetTexImage( 	GLenum target,
                       GLint level,
                       GLenum format,
                       GLenum type,
                       void * pixels);

void glGetQueryObjectiv( 	GLuint id,
                            GLenum pname,
                            GLint * params);

// GLES 3.0 core query functions. Implemented in query.c so eglGetProcAddress
// returns a real forwarder instead of an empty STUBFUNC (see query.c comment).
void glGenQueries(GLsizei n, GLuint* ids);
void glDeleteQueries(GLsizei n, const GLuint* ids);
GLboolean glIsQuery(GLuint id);
void glBeginQuery(GLenum target, GLuint id);
void glEndQuery(GLenum target);
void glGetQueryiv(GLenum target, GLenum pname, GLint* params);
void glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint* params);

void glDepthRange(GLdouble nearVal,
                  GLdouble farVal);

void glGetFloatv(GLenum pname, GLfloat* data);

GLESOVERRIDE(glClearDepth)
GLESOVERRIDE(glMapBuffer)
GLESOVERRIDE(glGetTexLevelParameteriv)
GLESOVERRIDE(glGetTexLevelParameterfv)
GLESOVERRIDE(glCreateShader)
GLESOVERRIDE(glDeleteShader)
GLESOVERRIDE(glCreateProgram)
GLESOVERRIDE(glDeleteProgram)
GLESOVERRIDE(glLinkProgram)
GLESOVERRIDE(glAttachShader)
GLESOVERRIDE(glGetShaderiv)
GLESOVERRIDE(glShaderSource)
GLESOVERRIDE(glTexImage2D)
GLESOVERRIDE(glDebugMessageControl)
GLESOVERRIDE(glGetString)
GLESOVERRIDE(glEnable)
GLESOVERRIDE(glMultiDrawArrays)
GLESOVERRIDE(glMultiDrawElements)
GLESOVERRIDE(glMultiDrawElementsBaseVertex)
GLESOVERRIDE(glDrawElementsBaseVertex)
GLESOVERRIDE(glBindBufferBase)
GLESOVERRIDE(glBindBufferRange)
GLESOVERRIDE(glBindBuffer)
GLESOVERRIDE(glGenBuffers)
GLESOVERRIDE(glDeleteBuffers)
GLESOVERRIDE(glIsBuffer)
GLESOVERRIDE(glBufferData)
GLESOVERRIDE(glBufferSubData)
GLESOVERRIDE(glUnmapBuffer)
GLESOVERRIDE(glGetBufferParameteriv)
GLESOVERRIDE(glGetBufferPointerv)
GLESOVERRIDE(glUseProgram)
GLESOVERRIDE(glGetIntegerv)
GLESOVERRIDE(glGetFloatv)
GLESOVERRIDE(glBindFramebuffer)
GLESOVERRIDE(glGenFramebuffers)
GLESOVERRIDE(glDeleteFramebuffers)
GLESOVERRIDE(glFramebufferTexture2D)
GLESOVERRIDE(glFramebufferTextureLayer)
GLESOVERRIDE(glFramebufferRenderbuffer)
GLESOVERRIDE(glGetFramebufferAttachmentParameteriv)
GLESOVERRIDE(glDrawBuffers)
GLESOVERRIDE(glDrawBuffer)
GLESOVERRIDE(glClearBufferiv)
GLESOVERRIDE(glClearBufferuiv)
GLESOVERRIDE(glClearBufferfv)
GLESOVERRIDE(glCheckFramebufferStatus)
GLESOVERRIDE(glReadPixels)
GLESOVERRIDE(glTexSubImage2D)
GLESOVERRIDE(glCopyTexSubImage2D)
GLESOVERRIDE(glTexParameteri)
GLESOVERRIDE(glBindFragDataLocation)
GLESOVERRIDE(glGetTexImage)
GLESOVERRIDE(glGetQueryObjectiv)
GLESOVERRIDE(glGetQueryObjecti64v)
GLESOVERRIDE(glGetQueryObjectui64v)
GLESOVERRIDE(glGenQueries)
GLESOVERRIDE(glDeleteQueries)
GLESOVERRIDE(glIsQuery)
GLESOVERRIDE(glBeginQuery)
GLESOVERRIDE(glEndQuery)
GLESOVERRIDE(glGetQueryiv)
GLESOVERRIDE(glGetQueryObjectuiv)
GLESOVERRIDE(glDepthRange)
GLESOVERRIDE(glVertexAttrib1d)
GLESOVERRIDE(glVertexAttrib1dv)
GLESOVERRIDE(glVertexAttrib1s)
GLESOVERRIDE(glVertexAttrib1sv)
GLESOVERRIDE(glVertexAttrib2d)
GLESOVERRIDE(glVertexAttrib2dv)
GLESOVERRIDE(glVertexAttrib2s)
GLESOVERRIDE(glVertexAttrib2sv)
GLESOVERRIDE(glVertexAttrib3d)
GLESOVERRIDE(glVertexAttrib3dv)
GLESOVERRIDE(glVertexAttrib3s)
GLESOVERRIDE(glVertexAttrib3sv)
GLESOVERRIDE(glVertexAttrib4d)
GLESOVERRIDE(glVertexAttrib4dv)
GLESOVERRIDE(glVertexAttrib4s)
GLESOVERRIDE(glVertexAttrib4sv)
GLESOVERRIDE(glVertexAttrib4Nbv)
GLESOVERRIDE(glVertexAttrib4Niv)
GLESOVERRIDE(glVertexAttrib4Nsv)
GLESOVERRIDE(glVertexAttrib4Nub)
GLESOVERRIDE(glVertexAttrib4Nubv)
GLESOVERRIDE(glVertexAttrib4Nuiv)
GLESOVERRIDE(glVertexAttrib4Nusv)
GLESOVERRIDE(glVertexAttribI1i)
GLESOVERRIDE(glVertexAttribI1iv)
GLESOVERRIDE(glVertexAttribI1ui)
GLESOVERRIDE(glVertexAttribI1uiv)
GLESOVERRIDE(glVertexAttribI2i)
GLESOVERRIDE(glVertexAttribI2iv)
GLESOVERRIDE(glVertexAttribI2ui)
GLESOVERRIDE(glVertexAttribI2uiv)
GLESOVERRIDE(glVertexAttribI3i)
GLESOVERRIDE(glVertexAttribI3iv)
GLESOVERRIDE(glVertexAttribI3ui)
GLESOVERRIDE(glVertexAttribI3uiv)
GLESOVERRIDE(glVertexAttribI4bv)
GLESOVERRIDE(glVertexAttribI4ubv)
GLESOVERRIDE(glVertexAttribI4sv)
GLESOVERRIDE(glVertexAttribI4usv)
GLESOVERRIDE(glBufferStorage)
GLESOVERRIDE(glGetStringi)
GLESOVERRIDE(glTexParameterf)
GLESOVERRIDE(glTexParameteri)
GLESOVERRIDE(glTexParameterfv)
GLESOVERRIDE(glTexParameteriv)
GLESOVERRIDE(glTexParameterIiv)
GLESOVERRIDE(glTexParameterIuiv)
GLESOVERRIDE(glRenderbufferStorage)
GLESOVERRIDE(glGetError)
GLESOVERRIDE(glTexBuffer)
GLESOVERRIDE(glTexBufferRange)
GLESOVERRIDE(glMapBufferRange)
GLESOVERRIDE(glFlushMappedBufferRange)

// GLES 2.0/3.0 core static-entry forwarders. ANGLE need not export these
// through eglGetProcAddress, so without GLESOVERRIDE LTW handed out empty
// STUBFUNC no-ops (see stubs.c) and MC rendering silently broke. Each name
// below resolves to the thin forwarder implemented in main.c / shader_wrapper.c
// / vertexattrib.c / framebuffer.c, which calls the host pointer already
// resolved into es3_functions at init. No forward declarations are needed
// here: GLES3/gl32.h (included via proc.h) already declares every one of
// these ES3 core prototypes -- same reason glGenBuffers above has no decl.
GLESOVERRIDE(glActiveTexture)
GLESOVERRIDE(glBeginTransformFeedback)
GLESOVERRIDE(glBindRenderbuffer)
GLESOVERRIDE(glBindSampler)
GLESOVERRIDE(glBindTexture)
GLESOVERRIDE(glBindTransformFeedback)
GLESOVERRIDE(glBindVertexArray)
GLESOVERRIDE(glBlendColor)
GLESOVERRIDE(glBlendEquation)
GLESOVERRIDE(glBlendEquationSeparate)
GLESOVERRIDE(glBlendFunc)
GLESOVERRIDE(glBlendFuncSeparate)
GLESOVERRIDE(glBlitFramebuffer)
GLESOVERRIDE(glClear)
GLESOVERRIDE(glClearBufferfi)
GLESOVERRIDE(glClearColor)
GLESOVERRIDE(glClearDepthf)
GLESOVERRIDE(glClearStencil)
GLESOVERRIDE(glClientWaitSync)
GLESOVERRIDE(glColorMask)
GLESOVERRIDE(glCompressedTexImage2D)
GLESOVERRIDE(glCompressedTexImage3D)
GLESOVERRIDE(glCompressedTexSubImage2D)
GLESOVERRIDE(glCompressedTexSubImage3D)
GLESOVERRIDE(glCopyBufferSubData)
GLESOVERRIDE(glCopyTexImage2D)
GLESOVERRIDE(glCopyTexSubImage3D)
GLESOVERRIDE(glCullFace)
GLESOVERRIDE(glDeleteRenderbuffers)
GLESOVERRIDE(glDeleteSamplers)
GLESOVERRIDE(glDeleteSync)
GLESOVERRIDE(glDeleteTransformFeedbacks)
GLESOVERRIDE(glDeleteVertexArrays)
GLESOVERRIDE(glDepthFunc)
GLESOVERRIDE(glDepthMask)
GLESOVERRIDE(glDepthRangef)
GLESOVERRIDE(glDisable)
GLESOVERRIDE(glDrawArrays)
GLESOVERRIDE(glDrawArraysInstanced)
GLESOVERRIDE(glDrawElements)
GLESOVERRIDE(glDrawElementsInstanced)
GLESOVERRIDE(glDrawRangeElements)
GLESOVERRIDE(glEndTransformFeedback)
GLESOVERRIDE(glFenceSync)
GLESOVERRIDE(glFinish)
GLESOVERRIDE(glFlush)
GLESOVERRIDE(glFrontFace)
GLESOVERRIDE(glGenRenderbuffers)
GLESOVERRIDE(glGenSamplers)
GLESOVERRIDE(glGenTextures)
GLESOVERRIDE(glGenTransformFeedbacks)
GLESOVERRIDE(glGenVertexArrays)
GLESOVERRIDE(glGenerateMipmap)
GLESOVERRIDE(glGetActiveUniformBlockName)
GLESOVERRIDE(glGetActiveUniformBlockiv)
GLESOVERRIDE(glGetActiveUniformsiv)
GLESOVERRIDE(glGetBooleanv)
GLESOVERRIDE(glGetBufferParameteri64v)
GLESOVERRIDE(glGetFragDataLocation)
GLESOVERRIDE(glGetInteger64i_v)
GLESOVERRIDE(glGetInteger64v)
GLESOVERRIDE(glGetIntegeri_v)
GLESOVERRIDE(glGetInternalformativ)
GLESOVERRIDE(glGetProgramBinary)
GLESOVERRIDE(glGetRenderbufferParameteriv)
GLESOVERRIDE(glGetSamplerParameterfv)
GLESOVERRIDE(glGetSamplerParameteriv)
GLESOVERRIDE(glGetShaderPrecisionFormat)
GLESOVERRIDE(glGetSynciv)
GLESOVERRIDE(glGetTexParameterfv)
GLESOVERRIDE(glGetTexParameteriv)
GLESOVERRIDE(glGetTransformFeedbackVarying)
GLESOVERRIDE(glGetUniformBlockIndex)
GLESOVERRIDE(glGetUniformIndices)
GLESOVERRIDE(glGetUniformuiv)
GLESOVERRIDE(glGetVertexAttribIiv)
GLESOVERRIDE(glGetVertexAttribIuiv)
GLESOVERRIDE(glHint)
GLESOVERRIDE(glInvalidateFramebuffer)
GLESOVERRIDE(glInvalidateSubFramebuffer)
GLESOVERRIDE(glIsEnabled)
GLESOVERRIDE(glIsFramebuffer)
GLESOVERRIDE(glIsRenderbuffer)
GLESOVERRIDE(glIsSampler)
GLESOVERRIDE(glIsSync)
GLESOVERRIDE(glIsTexture)
GLESOVERRIDE(glIsTransformFeedback)
GLESOVERRIDE(glIsVertexArray)
GLESOVERRIDE(glLineWidth)
GLESOVERRIDE(glPauseTransformFeedback)
GLESOVERRIDE(glPixelStorei)
GLESOVERRIDE(glPolygonOffset)
GLESOVERRIDE(glProgramBinary)
GLESOVERRIDE(glProgramParameteri)
GLESOVERRIDE(glReadBuffer)
GLESOVERRIDE(glReleaseShaderCompiler)
GLESOVERRIDE(glRenderbufferStorageMultisample)
GLESOVERRIDE(glResumeTransformFeedback)
GLESOVERRIDE(glSampleCoverage)
GLESOVERRIDE(glSamplerParameterf)
GLESOVERRIDE(glSamplerParameterfv)
GLESOVERRIDE(glSamplerParameteri)
GLESOVERRIDE(glSamplerParameteriv)
GLESOVERRIDE(glScissor)
GLESOVERRIDE(glShaderBinary)
GLESOVERRIDE(glStencilFunc)
GLESOVERRIDE(glStencilFuncSeparate)
GLESOVERRIDE(glStencilMask)
GLESOVERRIDE(glStencilMaskSeparate)
GLESOVERRIDE(glStencilOp)
GLESOVERRIDE(glStencilOpSeparate)
GLESOVERRIDE(glTexImage3D)
GLESOVERRIDE(glTexStorage2D)
GLESOVERRIDE(glTexStorage3D)
GLESOVERRIDE(glTexSubImage3D)
GLESOVERRIDE(glTransformFeedbackVaryings)
GLESOVERRIDE(glUniform1f)
GLESOVERRIDE(glUniform1fv)
GLESOVERRIDE(glUniform1i)
GLESOVERRIDE(glUniform1iv)
GLESOVERRIDE(glUniform1ui)
GLESOVERRIDE(glUniform1uiv)
GLESOVERRIDE(glUniform2f)
GLESOVERRIDE(glUniform2fv)
GLESOVERRIDE(glUniform2i)
GLESOVERRIDE(glUniform2iv)
GLESOVERRIDE(glUniform2ui)
GLESOVERRIDE(glUniform2uiv)
GLESOVERRIDE(glUniform3f)
GLESOVERRIDE(glUniform3fv)
GLESOVERRIDE(glUniform3i)
GLESOVERRIDE(glUniform3iv)
GLESOVERRIDE(glUniform3ui)
GLESOVERRIDE(glUniform3uiv)
GLESOVERRIDE(glUniform4f)
GLESOVERRIDE(glUniform4fv)
GLESOVERRIDE(glUniform4i)
GLESOVERRIDE(glUniform4iv)
GLESOVERRIDE(glUniform4ui)
GLESOVERRIDE(glUniform4uiv)
GLESOVERRIDE(glUniformBlockBinding)
GLESOVERRIDE(glUniformMatrix2fv)
GLESOVERRIDE(glUniformMatrix2x3fv)
GLESOVERRIDE(glUniformMatrix2x4fv)
GLESOVERRIDE(glUniformMatrix3fv)
GLESOVERRIDE(glUniformMatrix3x2fv)
GLESOVERRIDE(glUniformMatrix3x4fv)
GLESOVERRIDE(glUniformMatrix4fv)
GLESOVERRIDE(glUniformMatrix4x2fv)
GLESOVERRIDE(glUniformMatrix4x3fv)
GLESOVERRIDE(glVertexAttrib1f)
GLESOVERRIDE(glVertexAttrib1fv)
GLESOVERRIDE(glVertexAttrib2f)
GLESOVERRIDE(glVertexAttrib2fv)
GLESOVERRIDE(glVertexAttrib3f)
GLESOVERRIDE(glVertexAttrib3fv)
GLESOVERRIDE(glVertexAttrib4f)
GLESOVERRIDE(glVertexAttrib4fv)
GLESOVERRIDE(glVertexAttribDivisor)
GLESOVERRIDE(glVertexAttribI4i)
GLESOVERRIDE(glVertexAttribI4iv)
GLESOVERRIDE(glVertexAttribI4ui)
GLESOVERRIDE(glVertexAttribI4uiv)
GLESOVERRIDE(glVertexAttribIPointer)
GLESOVERRIDE(glVertexAttribPointer)
GLESOVERRIDE(glViewport)
GLESOVERRIDE(glWaitSync)
GLESOVERRIDE(glBindAttribLocation)
GLESOVERRIDE(glCompileShader)
GLESOVERRIDE(glDeleteTextures)
GLESOVERRIDE(glDetachShader)
GLESOVERRIDE(glDisableVertexAttribArray)
GLESOVERRIDE(glEnableVertexAttribArray)
GLESOVERRIDE(glGetActiveAttrib)
GLESOVERRIDE(glGetActiveUniform)
GLESOVERRIDE(glGetAttachedShaders)
GLESOVERRIDE(glGetAttribLocation)
GLESOVERRIDE(glGetProgramInfoLog)
GLESOVERRIDE(glGetProgramiv)
GLESOVERRIDE(glGetShaderInfoLog)
GLESOVERRIDE(glGetShaderSource)
GLESOVERRIDE(glGetUniformLocation)
GLESOVERRIDE(glGetUniformfv)
GLESOVERRIDE(glGetUniformiv)
GLESOVERRIDE(glGetVertexAttribPointerv)
GLESOVERRIDE(glGetVertexAttribfv)
GLESOVERRIDE(glGetVertexAttribiv)
GLESOVERRIDE(glIsProgram)
GLESOVERRIDE(glIsShader)
GLESOVERRIDE(glValidateProgram)
